import os

GSHEET_CLIENT_ID = os.getenv("GSHEET_CLIENT_ID")
GSHEET_CLIENT_EMAIL = os.getenv("GSHEET_CLIENT_EMAIL")
GSHEET_PRIVATE_KEY_ID = os.getenv("GSHEET_PRIVATE_KEY_ID")
GSHEET_PRIVATE_KEY = os.getenv("GSHEET_PRIVATE_KEY")
